ministryofjustice/hmpps-resettlement-passport-ui

- assets/js/finance-id.js
- server/views/pages/finance-id.njk
FEAT: toggle show/hide delete confirmation buttons
REFACTOR: temporarily replace `form` element with a `div` to avoid submission errors
> FEAT: show/hide assessment delete buttons

- assets/js/finance-id.js
When there is no assessment, the delete button for banking application does not work
Add event listeners conditionally
> FIX: enable delete bank application when no assessment

- server/views/pages/overview.njk
[RP2-641 ](https://project-moj.atlassian.net/browse/RP2-641)
FIX: replace empty tags with "No data" message if no data
> FIX: replace tags with message if no risk data

- .circleci/config.yml
- helm_deploy/hmpps-resettlement-passport-ui/Chart.yaml
- helm_deploy/hmpps-resettlement-passport-ui/values.yaml
- helm_deploy/values-preprod.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
2 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal,prisons,private_prisons`
- The size of the allowlist defined in this file will change: `45 => 0 (45 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
- sodexo1
- sodexo2
- sodexo3
- oakwood-3
- oakwood-4
The following IPs have been identified as …
> Migrating project to use groups in allowlist

- server/config.ts
6 secs because it meets out 95 percentile on a average day. but we should review this fairly often
> RP2-689: reduce timeout to 6 seconds on rp client

- server/data/model/BCST2Form.ts
- server/utils/formatAssessmentResponse.ts
- server/views/macros/checkAnswers.njk
- server/views/macros/radio-with-address.njk
- server/views/pages/BCST2-form.njk
**Changes made:**
- Conditionally nest and reveal the address fields inside the radio buttons - first two options only.
- Persist input data and pre-populate with existing answers when navigating back
- If you select the first radio button, fill in some address data, then change radio button and fill in data again, it should only persist data from the selected radio button, any address answers from the other parent radio button should be ignored.
- Display the Address answers in the check answers page - given values only
> PSFR-1026: format and persist address fields.

- docker-compose-test.yml
- docker-compose.yml
- helm_deploy/hmpps-resettlement-passport-ui/Chart.yaml
- helm_deploy/hmpps-resettlement-passport-ui/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
We need to generate PDF from HTML markup for [PLT-42](https://project-moj.atlassian.net/browse/PLT-42),
gotenberg seems to be used in another 4 repositories that I can count from the MOJ group, I have done some analysis prior to this and I would like to use gotenberg here too.
Analysis below:
----------------------------------
Intro: the aim is to dynamically generate a PDF that looks like https://rp-prototype-main.apps.live.cloud-platform.service.justice.gov.uk/public/images/passport-non-digital/paper%20prototype%20v3.pdf. (design now outdated see Jira ticket instead)
There are some challenges to this specific PDF format
Challenged to consider:
- Custom styling, ideally provided as HTML + CSS by designers for easier maintainability, it’s not ideal to try and reproduce from a PDF 
- …
> Add gotenberg to deployment setup

- server/routes/BCST2-form/BCST2FormController.ts
- server/routes/BCST2-form/BCST2FormView.ts
- server/views/pages/BCST2-form.njk
AC5 - Edit form response - second question onwards
Given the user has clicked to edit a form response for any question in the Resettlement Assessment form
And has already submitted the first selected question
And is on a subsequent question page
When clicking the ‘Back’ link
Then direct the user to the previous question page
> PSFR-1014: Fix for AC5

- server/views/pages/printPack.njk
When a prisoner has no appointments the PDF looks wrong,
it should say: 
- page 1 of 2 on page 1
- a text that states “ you have no appointments “on page 2
- page 2 of 2 on page 2
- no page 3
> [PLT-148] fix pdf with no appointments

- server/routes/immediate-needs-report/immediateNeedsReportController.test.ts
- server/routes/immediate-needs-report/immediateNeedsReportController.ts
On post submit edit, it was always defaulting to version 1, and if the assessment in the db was any other version an error would be thrown
> PSFR-1591 Fix using version 1 when editing

- server/@types/express/index.d.ts
- server/routes/accommodation/__snapshots__/accommodationController.test.ts.snap
- server/routes/attitudes-thinking-behaviour/__snapshots__/attitudesThinkingBehaviourController.test.ts.snap
- server/routes/children-families-and-communities/__snapshots__/childrenFamiliesCommunitiesController.test.ts.snap
- server/routes/drugs-alcohol/__snapshots__/drugsAlcoholController.test.ts.snap
- server/routes/education-skills-work/__snapshots__/educationSkillsWorkController.test.ts.snap
- server/routes/finance-id/__snapshots__/financeIdController.test.ts.snap
- server/routes/health-status/__snapshots__/healthStatusController.test.ts.snap
- server/routes/support-needs/index.ts
- server/routes/support-needs/supportNeedsController.test.ts
- server/routes/support-needs/supportNeedsController.ts
- server/routes/testutils/testUtils.ts
- server/views/partials/supportNeedsSummary.njk
* removed the "add support need" links for legacy profiles
* blocked access to support need routes for legacy profiles
> RSP-1849: Block support needs for legacy profiles

- localstack/config.json
- server/@types/express/index.d.ts
- server/routes/configHelperTest.ts
- server/routes/support-need-update/__snapshots__/supportNeedUpdateController.test.ts.snap
- server/routes/support-need-update/supportNeedUpdateController.ts
- server/routes/support-need-update/supportNeedUpdateView.ts
- server/views/pages/update-support-need.njk
When editing an existing support need, you can now see all previous updates via a [details component](https://design-system.service.gov.uk/components/details/) at the top of the page.
There is also a [warning text component](https://design-system.service.gov.uk/components/warning-text/) which mentions the release date for support needs - this is pulled from config.
> RSP-1863: Added previous updates to update support needs page

- server/routes/staffDashboard/__snapshots__/staffDashboardController.test.ts.snap
- server/views/macros/prisoners-table.njk
When supportNeeds is enabled, the 'Last Updated' link in the prisoner table now links to the 'Support needs statuses' panel on the prisoner overview page, instead of to the top of the page.
> RSP-1866: Set 'Last Updated' link on prisoner search page to 'Support needs statuses' panel

- server/routes/accommodation/__snapshots__/accommodationController.test.ts.snap
- server/routes/attitudes-thinking-behaviour/__snapshots__/attitudesThinkingBehaviourController.test.ts.snap
- server/routes/children-families-and-communities/__snapshots__/childrenFamiliesCommunitiesController.test.ts.snap
- server/routes/drugs-alcohol/__snapshots__/drugsAlcoholController.test.ts.snap
- server/routes/education-skills-work/__snapshots__/educationSkillsWorkController.test.ts.snap
- server/routes/finance-id/__snapshots__/financeIdController.test.ts.snap
- server/routes/health-status/__snapshots__/healthStatusController.test.ts.snap
- server/routes/prisoner-overview/__snapshots__/prisonerOverviewController.test.ts.snap
- server/views/pages/overview.njk
- server/views/partials/caseNote.njk
- server/views/partials/caseNotes.njk
Remove excess whitespace from the top of case notes on the prisoner overview page, by refactoring the code to remove if/else clause from within the 'show-line-breaks' tag.
Also factored out the case note code into a separate caseNote.njk file, so it can be used by both the prisoner overview and the pathways pages instead of duplicating code.
> RSP-1911: Remove excess whitespace at the top of case notes.

- server/routes/support-needs/__snapshots__/supportNeedsController.test.ts.snap
- server/routes/support-needs/supportNeedsController.test.ts
- server/routes/support-needs/supportNeedsController.ts
- server/views/pages/support-needs-check-answers.njk
- server/views/pages/support-needs-error.njk
- server/views/pages/support-needs-status.njk
- server/views/pages/support-needs.njk
- Add custom error page if deleted support need is re-navigated to (also fixes RSP-1970)
- Send user to Something went wrong page if try to navigate to non-existent support need uuid
- Fix page titles for support needs pages
- Fix issue with missing prisonerNumber or unhandled error crashing node app in validation middleware
> RSP-1967 Add error page for support need update not found

- server/routes/accommodation/__snapshots__/accommodationController.test.ts.snap
- server/routes/accommodation/accommodationController.test.ts
- server/routes/attitudes-thinking-behaviour/__snapshots__/attitudesThinkingBehaviourController.test.ts.snap
- server/routes/children-families-and-communities/__snapshots__/childrenFamiliesCommunitiesController.test.ts.snap
- server/routes/drugs-alcohol/__snapshots__/drugsAlcoholController.test.ts.snap
- server/routes/education-skills-work/__snapshots__/educationSkillsWorkController.test.ts.snap
- server/routes/finance-id/__snapshots__/financeIdController.test.ts.snap
- server/routes/health-status/__snapshots__/healthStatusController.test.ts.snap
- server/views/partials/supportNeedsSummary.njk
- server/views/partials/supportNeedsUpdates.njk
When viewing a pathway there are two information links for the support needs updates:
1. On the Support Needs summary card: "New support needs cannot be added for this person. **Find out why.**"
2. On the pathway summary card "Some updates may not be linked to a support need as they were created before support needs were added to PSfR. **Find out more about this update.**"
Both of these links have been updated to point at the **/service-updates/support-needs** page
_(Note: testing note - the first link will only show when viewing a legacy profile)_
> RSP-1988: Update support needs information links

- package-lock.json
- package.json
- server/__snapshots__/errorHandler.test.ts.snap
Update govuk-frontend to version 5.10.0 (latest version).
> RSP-2044: Update govuk-frontend version to fix security pipeline

- server/utils/utils.test.ts
- server/utils/utils.ts
Back button in 'Add Support needs' journey should restrict navigation back to selected AND status updatable needs.
> [RSP-2043] Support needs back button defect fix

- server/routes/accommodation/accommodationController.ts
- server/routes/accommodation/index.ts
- server/routes/attitudes-thinking-behaviour/attitudesThinkingBehaviourController.ts
- server/routes/attitudes-thinking-behaviour/index.ts
- server/routes/children-families-and-communities/childrenFamiliesCommunitiesController.ts
- server/routes/children-families-and-communities/index.ts
- server/routes/drugs-alcohol/drugsAlcoholController.ts
- server/routes/drugs-alcohol/index.ts
- server/routes/education-skills-work/educationSkillsWorkController.ts
- server/routes/education-skills-work/index.ts
- server/routes/finance-id/financeIdController.ts
- server/routes/finance-id/index.ts
- server/routes/health-status/healthStatusController.ts
- server/routes/health-status/index.ts
- server/routes/validation.ts
- server/utils/utils.ts
- Move validation of `supportNeedUpdateSort` field out of individual pathway pages and into common utility function. 
- Remove validation of non-existent `supportNeedUpdateFilter` field from accommodation page
> RSP-2008: Refactor validation of pathway params

- server/routes/prisoner-overview/__snapshots__/prisonerOverviewController.test.ts.snap
- server/routes/prisoner-overview/prisonerOverviewController.test.ts
- server/routes/reset-profile/index.ts
- server/views/macros/tasks-details.njk
- server/views/pages/overview.njk
When in read-only mode:
- Remove 'reset profile' button.  (If this means the 'Actions' box will be empty, also remove the box)
- Send all related routes to 404 read-only page.
> RSP-2050 Remove 'reset profile' button and routes when read-only

- server/routes/staffDashboard/staffDashboardController.test.ts
Added some UTs to confirm the tabs are shown / hidden depending on if the site is in read only mode or not
> RSP-2047: Added UT for assign a case / staff capacity tab toggling

- .github/workflows/node_end_to_end_test.yml
Fixes playwright version to 1.54.1 in the e2e test, to ensure compatibility between playwright/chromium versions in the e2e test and cucumber.
> Fix playwright version to 1.54.1 in e2e test
