server/routes/index.ts
server/views/macros/pathway-subnav.njk
server/views/macros/title-and-intro.njk
server/views/pages/accommodation.njk
server/views/pages/attitudes-thinking-behaviour.njk
server/views/pages/children-families-communities.njk
server/views/pages/drugs-alcohol.njk
server/views/pages/education-skills-work.njk
server/views/pages/finance-id.njk
server/views/pages/health.njk
server/views/pages/prisoner-profile.njk
server/views/partials/layout.njk

Fetch and pass data from API endpoint

Rp 303 display licence conditions

---

server/utils/constants.ts

update status page: change descriptions for states

FIX: update to new status descriptions

---

server/utils/utils.ts
server/views/partials/profileHeader.njk

Display "... days ago" if release date is in the past
Display "... days" if release date is in the future

FIX: check if date is in past

---

server/views/macros/prisoners-table.njk

Small change to add a span element and an id to the "lastUpdated" cell

REFACTOR: add span and id to assist with testing

---

assets/js/scrollToCaseNotes.js
server/routes/index.ts
server/views/pages/overview.njk
server/views/pages/staff-dashboard.njk
server/views/partials/layout.njk

FEAT: filter and sort case notes by pathway, date and sort type
FEAT: scroll to case notes section on pagination change and on filter selection (requires frontend JS as we can't use anchor links when rendering from Express)
FIX: remove unused JS files in the layout file causing errors
FIX: inline style errors

FEAT: filter and sort case notes by pathway, date and sort type

---

assets/scss/local.scss
server/routes/index.ts
server/views/pages/accommodation.njk
server/views/pages/attitudes-thinking-behaviour.njk
server/views/pages/education-skills-work.njk
server/views/pages/finance-id.njk
server/views/pages/health.njk
server/views/pages/overview.njk
server/views/pages/status-update.njk

FEAT: sticky anchor links navigation
FIX: add case notes to anchor links
FIX:  case notes - default to "All" pathways on initial page load

FEAT: sticky anchor links navigation

---

server/routes/index.ts
server/views/pages/status-update.njk

FEAT: fetch case notes creators list and display in a Select dropdown

FEAT: fetch creator list. Select dropdown

---

assets/js/scrollToCaseNotes.js
server/routes/index.ts
server/views/macros/pagination.njk
server/views/pages/overview.njk

FIX: replace frontend JS with anchor links for pagination and filters
FIX: persist filter selection with pagination

FIX: persist filter selection with pagination

---

server/views/pages/overview.njk

FIX: replace days with weeks in the date range dropdown

FIX: replace days with weeks in the date range filter

---

server/routes/index.ts
server/utils/utils.ts
server/views/macros/status-details.njk
server/views/pages/add-case-note.njk
server/views/pages/overview.njk

FEAT: new page for creating new case notes
REFACTOR: change path params to query params

FEAT: page for creating new case notes

---

server/views/pages/overview.njk

small fix to change order of pathways

FIX: change pathways sorting to ascending order

---

server/views/pages/status-update.njk

FIX: change form action url to work with query params

FIX: change form action url to query params

---

assets/js/finance-id.js
server/routes/finance-id/index.ts
server/routes/finance-id/update-status-bank-account.ts
server/routes/index.ts
server/views/pages/add-bank-account-confirm.njk
server/views/pages/add-bank-account-update-status.njk
server/views/pages/add-bank-account.njk
server/views/pages/add-id-update.njk
server/views/pages/assessment-confirmation.njk
server/views/pages/assessment.njk
server/views/pages/finance-id.njk

FEAT: fetch bank application
FEAT: display bank application
FEAT: delete bank application
REFACTOR: financeId router to accommodate multiple api calls
REFACTOR: JavaScript for toggle buttons
STYLE: page sub headings to `h3` and `heading-m`
STYLE: UI for the status update page

FEAT: fetch, display, and delete banking application

---

server/routes/staffDashboard/staffDashboardController.ts
server/routes/staffDashboard/staffDashboardView.ts
server/services/prisonService.ts
server/views/pages/staff-dashboard.njk

FEAT: filter by time to release
FEAT: defaults prisoner list results to apply the "12 weeks" filter
**NOTES**
1. Currently the dates of most prisoners are more than 24 weeks ago in the stub data, however the dev service data does contain dates within 24 weeks.
2. Test that the filters works when a name AND date filter is applied (using dev service api)

FEAT: filter prisoners list by time to release.

---

server/views/pages/finance-id.njk

FIX: order of anchor links in finance-id page

FIX: order of anchor links in finance-id page

---

server/views/pages/finance-id.njk

FIX: hide application buttons when application already exists

FIX: hide application buttons when application already exists

---

server/utils/utils.ts
server/views/pages/accommodation.njk
server/views/pages/add-bank-account-confirm.njk
server/views/pages/add-id-update-status-confirm.njk
server/views/pages/add-id-update-status.njk
server/views/pages/assessment-confirmation.njk
server/views/pages/finance-id.njk
server/views/pages/overview.njk

[RP2-692](https://project-moj.atlassian.net/browse/RP2-692)
Replaced abbreviated month format with long month format in applicable sections. (e.g. October instead of Oct)

Rp2 692/date formatting

---

server/views/pages/add-id-further.njk
server/views/pages/add-id.njk
server/views/pages/finance-id.njk

Disable option if IDType already has application
Fix incorrect Error surround for IDType

Disable IDType if an application already exists

---

server/views/pages/add-id-confirm.njk
server/views/pages/status-update.njk

RP2-692
FIX: change to long date format

RP2-692: FIX - change to long date format

---

server/routes/children-families-and-communities/childrenFamiliesCommunitiesController.ts
server/routes/children-families-and-communities/childrenFamiliesCommunitiesView.ts
server/routes/children-families-and-communities/index.ts
server/routes/index.ts
server/views/pages/children-families-communities.njk

Tested locally with 404, 500, 200 error codes

CRS referrals UI for children, families, communities

---

server/utils/utils.ts

[RP2-693](https://project-moj.atlassian.net/browse/RP2-693)
- Change time format to 24 hour
- Remove leading zeros

RP2-693: change to 24hr format and remove leading zeros

---

server/routes/index.ts
server/views/pages/status-update.njk

[RP2-670](https://project-moj.atlassian.net/browse/RP2-670): Display error message if patch request fails.

RP2-670: show error message if patch request fails

---

server/views/pages/education-skills-work.njk

**RP2 760**
Display table with current work status
Add data validation

RP2 760/current work status

---

server/config.ts
server/utils/nunjucksSetup.ts
server/views/partials/applicationInsightsScript.njk
server/views/partials/layout.njk

Added client side app insights script
Added toggle to not attempt to send clicks and page views from local

RP2-684: added client side app insights

---

server/views/macros/prisoners-table.njk

Anchor to "status" section in overview page
Fix dates not being displayed

RP2-856: FIX links anchor and not displaying text

---

server/routes/staffDashboard/staffDashboardController.ts
server/routes/staffDashboard/staffDashboardView.ts
server/views/macros/prisoners-table.njk
server/views/pages/staff-dashboard.njk

- Toggle sort by name, release date, release eligibility, pathway status, last updated date
- Conditionally hide ability to sort if pathway is not selected
- Persist sort options in pagination
- Reset pagination when new filter is selected
- Anchor to table when filtering and sorting

RP2-817: Sort prisoners table columns

---

assets/scss/local.scss
server/views/macros/prisoners-table.njk

- Prevent line wrapping by adding a no-wrap class
- Change "last updated" date to a short date

RP2-875: Force dates on one line

---

server/data/model/appointment.ts
server/data/model/appointmentErrorMessage.ts
server/routes/add-appointment/addAppointmentController.ts
server/routes/add-appointment/index.ts
server/utils/constants.ts
server/views/pages/add-appointment-confirm.njk
server/views/pages/add-appointment.njk

**Features**
- Form elements (need confirmation for content and error messaging)
- Populate input fields with pre-existing data when returning from check answers page or when failed validation
- Validation for required fields
- Validation for future date
- Persist data to check answers page
- Conditionally render table rows for the optional data (location and notes)
- Dynamic links back to appointment form elements
- Submit data to POST appointment and redirect user to the overview page appointments section
- Add BENEFITS to appointment type and to constants/enums

RP2-813 and RP2-815: Appointments form, confirm answers, validate

---

server/data/model/assessmentStatus.ts
server/routes/BCST2-form/BCST2FormController.ts
server/routes/BCST2-form/BCST2FormView.ts
server/routes/BCST2-form/index.ts
server/routes/assessment-complete/assessmentCompleteController.ts
server/routes/assessment-complete/assessmentCompleteView.ts
server/routes/assessment-complete/index.ts
server/routes/assessment-task-list/assessmentTaskListController.ts
server/routes/assessment-task-list/assessmentTaskListView.ts
server/routes/assessment-task-list/index.ts
server/routes/index.ts
server/utils/constants.ts
server/utils/nunjucksSetup.ts
server/utils/utils.ts
server/views/pages/BCST2-form.njk
server/views/pages/assessment-complete.njk
server/views/pages/assessment-task-list.njk
server/views/pages/overview.njk

**Changes made:**
- New layout for pages (headers and breadcrumbs)
- "Task list" page
- "Assessment complete" page
- Dynamic assessment statuses
- Banner on overview page for incomplete assessment
- New ENUMS and constants for assessment
- Enable & disable submit button conditionally (if ALL pathway statuses are complete)
- Feature flag for assessment banner notification

RP 887/BCST2

---

server/data/model/assessmentStatus.ts
server/routes/assessment-task-list/assessmentTaskListController.ts
server/routes/assessment-task-list/assessmentTaskListView.ts
server/services/rpService.ts
server/views/pages/assessment-task-list.njk

Replace hard coded array with the pathway assessments summary from API
Error handling & error messages

RP-968/assessment-task-list

---

server/@types/express/index.d.ts
server/routes/accommodation/accommodationController.ts
server/routes/accommodation/accommodationView.ts
server/routes/assessment-task-list/assessmentTaskListController.ts
server/routes/assessmentsSummaryMiddleware.ts
server/routes/attitudes-thinking-behaviour/attitudesThinkingBehaviourController.ts
server/routes/attitudes-thinking-behaviour/attitudesThinkingBehaviourView.ts
server/routes/children-families-and-communities/childrenFamiliesCommunitiesController.ts
server/routes/children-families-and-communities/childrenFamiliesCommunitiesView.ts
server/routes/drugs-alcohol/drugsAlcoholController.ts
server/routes/drugs-alcohol/drugsAlcoholView.ts
server/routes/education-skills-work/educationSkillsWorkController.ts
server/routes/education-skills-work/educationSkillsWorkView.ts
server/routes/finance-id/financeIdController.ts
server/routes/finance-id/financeIdView.ts
server/routes/health-status/healthStatusController.ts
server/routes/health-status/healthStatusView.ts
server/routes/index.ts
server/views/macros/incompleteBCST2.njk
server/views/pages/accommodation.njk
server/views/pages/attitudes-thinking-behaviour.njk
server/views/pages/children-families-communities.njk
server/views/pages/drugs-alcohol.njk
server/views/pages/education-skills-work.njk
server/views/pages/finance-id.njk
server/views/pages/health.njk
server/views/pages/overview.njk
server/views/partials/layout.njk

- Middleware uses the summary endpoint to provide the BCST2Completed status to all the routes and pathways
- Updated all pathway endpoints to pass down the req.BCST2Completed value
- In each pathway applied the following logic to the njk file
**If feature flag is off:**
Always display the page’s content
Always display the anchor links
Always display resettlement status box
Always display pathway description
Always hide the BCST2 alert box
**If feature flag is on and assessment is complete:**
Display the page’s content
Display the anchor links
Display resettlement status box
Display pathway description
Hide the BCST2 alert box
**If feature flag is on and assessment is incomplete:**
Hide the page’s content
Hide the anchor links
Hide resettlement status box
Hide pathway …

RP-982/BCST2-status-middleware

---

server/routes/assessmentsSummaryMiddleware.ts

Replace COMPLETE with SUBMITTED

RP-995/Replace COMPLETE with SUBMITTED

---

.circleci/config.yml

Updating environment variables in config

RP-841 Updating circleCI config to hopefully work

---

server/routes/BCST2-form/BCST2FormController.ts
server/routes/BCST2-form/index.ts
server/services/rpService.ts
server/utils/constants.ts
server/views/macros/checkAnswers.njk
server/views/pages/BCST2-form.njk

- Submit assessment (`/complete` endpoint)
- Error handling - show error page if fails
- Add status constants
- Style status tags
- Conditional form button action

submit assessment. status tag.

---

server/views/macros/checkAnswers.njk
server/views/macros/dropDown.njk
server/views/macros/listOfPeople.njk
server/views/macros/longText.njk
server/views/macros/radio-with-address.njk
server/views/macros/radio.njk
server/views/pages/BCST2-form.njk

- Check if question is first question of the page
- Use first question's title for page title

PSFR-1005: use question title instead of page title

---

server/routes/staffDashboard/staffDashboardController.ts
server/routes/staffDashboard/staffDashboardView.ts
server/services/rpService.ts
server/views/macros/radio-with-address.njk
server/views/pages/staff-dashboard.njk

**Changes made:**
- Add assessmentRequired param to `get` endpoint
- Only show filter if pathway status is "All"
- Retain filter status by appending new filter param to column sorting and pagination
- Fix formatting in the staff-dashboard `njk` file - (not complete)

PSFR-1035/filter assessment required

---

server/views/macros/checkbox.njk

PSFR-1084/fix when no existing answer

---

server/data/model/assessmentInformation.ts
server/routes/accommodation/accommodationController.ts
server/routes/accommodation/accommodationView.ts
server/routes/attitudes-thinking-behaviour/attitudesThinkingBehaviourController.ts
server/routes/attitudes-thinking-behaviour/attitudesThinkingBehaviourView.ts
server/routes/children-families-and-communities/childrenFamiliesCommunitiesController.ts
server/routes/children-families-and-communities/childrenFamiliesCommunitiesView.ts
server/routes/drugs-alcohol/drugsAlcoholController.ts
server/routes/drugs-alcohol/drugsAlcoholView.ts
server/routes/education-skills-work/educationSkillsWorkController.ts
server/routes/education-skills-work/educationSkillsWorkView.ts
server/routes/finance-id/financeIdController.ts
server/routes/finance-id/financeIdView.ts
server/routes/health-status/healthStatusController.ts
server/routes/health-status/healthStatusView.ts
server/services/rpService.ts
server/views/macros/assessmentInformation.njk
server/views/pages/accommodation.njk
server/views/pages/attitudes-thinking-behaviour.njk
server/views/pages/children-families-communities.njk
server/views/pages/drugs-alcohol.njk
server/views/pages/education-skills-work.njk
server/views/pages/finance-id.njk
server/views/pages/health.njk

- New `assessmentInformation` partial
- New `getAssessmentInformation` in `rpService`
- At the bottom of each pathway, display an Assessment information table
- Each question and answer should be displayed in it’s own row
- Display a date of last updated - formatted to long date (e.g. 15 September 2023)
- Display name for “last updated by”
- Error handling - display an error message if there was an error fetching the data (shouldn’t break rest of the page)
- Add "change" button links with `edit` parameter

fetch and display data in each pathway

---

server/views/pages/accommodation.njk
server/views/pages/attitudes-thinking-behaviour.njk
server/views/pages/children-families-communities.njk
server/views/pages/drugs-alcohol.njk
server/views/pages/education-skills-work.njk
server/views/pages/finance-id.njk
server/views/pages/health.njk

Add assessment information to subnav

PSFR-983: add assessment information to subnavs

---

server/data/model/BCST2Form.ts
server/routes/BCST2-form/BCST2FormController.ts
server/routes/BCST2-form/BCST2FormView.ts
server/utils/formatAssessmentResponse.ts
server/utils/nunjucksSetup.ts
server/utils/utils.test.ts
server/utils/utils.ts
server/utils/validateAssessmentResponse.test.ts
server/utils/validateAssessmentResponse.ts
server/views/macros/address.njk
server/views/macros/checkbox.njk
server/views/macros/dropDown.njk
server/views/macros/longText.njk
server/views/macros/radio.njk
server/views/macros/shortText.njk
server/views/macros/validationErrorMessage.njk
server/views/pages/BCST2-form.njk

**Validation**
- Questions marked as `MANDATORY` will redirect user back to current page if no answer is provided
- Validation logic for `ADDRESS` - only 1 required field
- Max character limits for `SHORT_TEXT` & `LONG_TEXT` fields (validation in TS, not in the `maxlength` html attribute)
- Unit tests for all of the above

PSFR-892: mandatory and max char validation

---

server/@types/express/index.d.ts
server/routes/BCST2-form/BCST2FormController.ts
server/views/macros/assessmentInformation.njk
server/views/macros/assessmentSummary.njk
server/views/macros/checkAnswers.njk
server/views/pages/BCST2-form.njk

Edit assessment link from table
Redirect to previous pathway on confirm
Hide case notes summary in check your answers page when editing assessment

PSFR-1038: Edit assessment. Redirect to pathway

---

integration_tests/e2e/otp.cy.ts
integration_tests/e2e/pdf.cy.ts
integration_tests/mockApis/rpApi.ts
server/services/rpService.ts

Delete otp call to backend not required

[PLT-42] fix otp calls sequence

---

server/data/model/assessmentInformation.ts
server/routes/BCST2-form/BCST2FormController.ts
server/routes/BCST2-form/BCST2FormView.ts
server/routes/assessment-complete/assessmentCompleteController.ts
server/routes/assessment-complete/assessmentCompleteView.ts
server/routes/assessment-task-list/assessmentTaskListController.ts
server/routes/assessment-task-list/assessmentTaskListView.ts
server/services/rpService.ts
server/utils/utils.ts
server/views/pages/BCST2-form.njk
server/views/pages/assessment-complete.njk
server/views/pages/assessment-task-list.njk
server/views/pages/overview.njk

* Add pre release task list
* Pass through pre release type to all steps of assessment

PSFR-1168 Pre release assessment

---

server/@types/express/index.d.ts
server/views/macros/preReleaseComplete.njk
server/views/macros/preReleaseRequired.njk
server/views/pages/overview.njk

- Notification box on Prisoner Overview page alerts PSO that pre-release assessment is required OR completed

PSFR-1123 - notification box on Prisoner Overview page 

---

server/routes/prisonerDetailsMiddleware.test.ts
server/routes/prisonerDetailsMiddleware.ts

Don't fail profile views when prisoner image cannot be resolved

PSFR-1226 Handle missing images

---

server/data/model/caseNotesCreators.ts
server/data/model/caseNotesHistory.ts
server/routes/accommodation/accommodationController.ts
server/routes/accommodation/accommodationView.ts
server/routes/attitudes-thinking-behaviour/attitudesThinkingBehaviourController.ts
server/routes/attitudes-thinking-behaviour/attitudesThinkingBehaviourView.ts
server/routes/children-families-and-communities/childrenFamiliesCommunitiesController.ts
server/routes/children-families-and-communities/childrenFamiliesCommunitiesView.ts
server/routes/drugs-alcohol/drugsAlcoholController.ts
server/routes/drugs-alcohol/drugsAlcoholView.ts
server/routes/education-skills-work/educationSkillsWorkController.ts
server/routes/education-skills-work/educationSkillsWorkView.ts
server/routes/finance-id/financeIdController.ts
server/routes/finance-id/financeIdView.ts
server/routes/health-status/healthStatusController.ts
server/routes/health-status/healthStatusView.ts
server/routes/index.ts
server/services/rpService.ts
server/views/macros/status-details.njk
server/views/pages/accommodation.njk
server/views/pages/attitudes-thinking-behaviour.njk
server/views/pages/children-families-communities.njk
server/views/pages/drugs-alcohol.njk
server/views/pages/education-skills-work.njk
server/views/pages/finance-id.njk
server/views/pages/health.njk
server/views/pages/status-update.njk
server/views/partials/caseNotes.njk

- Remove case notes history from "status update" page
- Remove anchor link from "status update" page
- Add case notes history to all pathway controllers and views
- Add case notes anchor link to all pathways
- Move case notes fetch into rpService
- Update styling in case note status component
- Query params to all pathways (pagination and filtering)
- When updating a status redirect user to pathway page

PSFR-1042: move case notes to pathways

---

server/utils/utils.test.ts
server/utils/utils.ts
server/views/partials/profileHeader.njk

Show - in release date in profile, and don't show days since epoch.

PSFR-1230 Handle null release dates

---

integration_tests/e2e/bcst2-report.cy.ts
integration_tests/mockApis/rpApi.ts
integration_tests/mockApis/scenarios/john-smith/john-smith-bcst2.ts

* Edit from check your answers page scenario
* Scenario with back button and divergent paths (currently set to skip as it is reproducing bug we want to fix)

PSFR-1220 Add more BSCT2 Cypress coverage

---

server/@types/express/index.d.ts
server/monitoring/customMetrics.ts
server/routes/print/printController.ts

this is for the PLT graphana dashboard

PLT-233 Add prison name to metrics

---

server/data/assessmentStateService.test.ts
server/data/assessmentStateService.ts
server/routes/BCST2-form/BCST2FormController.ts
server/views/macros/checkAnswers.njk
server/views/pages/BCST2-form.njk

* Send through submitted in the urls if we've already submitted
* Removed patch that attempted to fix resettlement report post complete edit, this should be fixed in api instead. Have raised separate ticket

PSFR-1220 Fix edit after submit, before complete

---

server/views/macros/checkAnswers.njk

To change links for case notes and pathway status

PSFR-1366 Add missing submitted flags

---

server/utils/nunjucksSetup.ts
server/views/pages/add-appointment-confirm.njk
server/views/pages/add-bank-account-confirm.njk
server/views/pages/add-id-confirm.njk
server/views/pages/finance-id.njk

In addition, get nunjucks to show some more info when running locally

PSFR-1363 Double click prevent on bank/id forms

---

server/data/assessmentStateService.ts
server/data/assessmentStore.ts
server/data/rpClient.ts
server/routes/immediate-needs-report/immediateNeedsReportController.test.ts
server/routes/immediate-needs-report/immediateNeedsReportController.ts
server/routes/immediate-needs-report/index.ts
server/routes/index.ts
server/routes/prisonerDetailsMiddleware.test.ts
server/routes/prisonerDetailsMiddleware.ts
server/routes/testutils/appSetup.ts
server/services/index.ts
server/services/rpService.test.ts
server/services/rpService.ts

- Redirect back to task list if submit is clicked with no answered questions
- Refactoring of `prisonerDetailsMiddleware` to enable unit testing `immediateNeedsReportController`

PSFR-1383 Don't submit when there is nothing answered

---

.eslintrc.json
cypress.config.ts
integration_tests/e2e/immediate-needs-report-report.cy.ts
integration_tests/e2e/pre-release-report.cy.ts
integration_tests/mockApis/redis.ts
integration_tests/mockApis/scenarios/john-smith/john-smith-immediate-needs-report.ts
integration_tests/mockApis/scenarios/john-smith/john-smith-pre-release.ts
server/config.ts
server/data/assessmentStateService.test.ts
server/data/assessmentStateService.ts
server/data/assessmentStore.ts
server/data/restClient.ts
server/routes/immediate-needs-report/immediateNeedsReportController.ts
server/utils/utils.ts
server/views/pages/assessment-task-list.njk

* Cache against userid instead of sessionid
* Increase ttl of keys to 5 days (up from until midnight of current day)
* When moving from task list into a pathway, check if in progress and move to the next question based on previous responses if it is
* Change Not started on task list page to Incomplete

PSFR-1213 Enable resuming a report entry

---

server/utils/nunjucksSetup.ts
server/utils/utils.ts
server/views/partials/profileHeader.njk

Remove incorrect age calculation

PSFR-1428 Use correctly calculated age from api

---

.circleci/config.yml
security_test/test_security.py

updated config to no longer store artifacts
updated test to only trigger failure on increase of medium to high severity
updated test to trigger warning (not fail) if granular change to previous results

updated zap test pipeline to no longer store report

---

integration_tests/mockApis/rpApi.ts
integration_tests/mockApis/scenarios/john-smith/john-smith-immediate-needs-report-edit.ts
integration_tests/mockApis/scenarios/john-smith/john-smith-immediate-needs-report.ts
integration_tests/mockApis/scenarios/john-smith/john-smith-pre-release.ts
integration_tests/mockApis/scenarios/john-smith/john-smith.ts
server/@types/express/index.d.ts
server/data/assessmentStateService.test.ts
server/data/assessmentStateService.ts
server/data/model/immediateNeedsReport.ts
server/routes/immediate-needs-report/immediateNeedsReportController.test.ts
server/routes/immediate-needs-report/immediateNeedsReportController.ts
server/services/rpService.ts
server/utils/constants.ts
server/utils/formatAssessmentResponse.ts

Reverts ministryofjustice/hmpps-resettlement-passport-ui#361

Revert "PSFR-1516: track reports version"

---

integration_tests/e2e/document-upload.cy.ts
integration_tests/mockApis/rpApi.ts
server/data/restClient.ts
server/data/rpClient.ts
server/services/documentService.test.ts
server/services/documentService.ts
server/views/pages/overview.njk
tsconfig.json

In addition set recommended typescript settings for our version of node (taken from https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping) and fix a couple of cases that got type errors afterwards.

PLT-480 Add missing information to documents table

---

server/views/macros/title-and-intro.njk
server/views/pages/overview.njk
server/views/partials/layout.njk
server/views/partials/profileHeader.njk

Fix csp error with document upload code

Add more data-qa attributes

---

assets/scss/local.scss
server/views/macros/checkbox.njk
server/views/macros/radio.njk
server/views/pages/immediate-needs-report.njk

Changes made:
- Back button font size to match prototype and govuk design system
- Add spacing between questions (radio and checkbox questions) to match prototype
- Fix spacing between page heading

PSFR-1604: adjust assessment spacing

---

integration_tests/flags.restore.json
localstack/flags.json
package.json
server/routes/immediate-needs-report/__snapshots__/immediateNeedsReportController.test.ts.snap
server/routes/immediate-needs-report/checkYourAnswersUtils.test.ts
server/routes/immediate-needs-report/checkYourAnswersUtils.ts
server/routes/immediate-needs-report/immediateNeedsReportController.test.ts
server/routes/immediate-needs-report/immediateNeedsReportController.ts
server/utils/nunjucksSetup.ts
server/views/pages/checkAnswers.njk
server/views/pages/immediate-needs-report.njk

Additionally - make it so changing nunjucks file / tests does not restart your node server when running in dev mode, and enable nunjucks watch for non prod envs

PSFR-1878 additional details default text

---

server/routes/immediate-needs-report/checkYourAnswersUtils.test.ts
server/routes/immediate-needs-report/checkYourAnswersUtils.ts
server/routes/immediate-needs-report/immediateNeedsReportController.ts
server/utils/nunjucksSetup.ts
server/utils/utils.test.ts
server/utils/utils.ts
server/views/macros/assessmentInformation.njk

pages. There's no IDs available from the backend here currently, so used title.

PSFR-1878 Default additional details on pathway

---

assets/scss/local.scss
server/data/model/pagination.ts
server/routes/assign-case/__snapshots__/assignCaseController.test.ts.snap
server/routes/assign-case/assignCaseController.test.ts
server/routes/assign-case/assignCaseController.ts
server/routes/assign-case/assignCaseView.ts
server/services/rpService.ts
server/utils/utils.test.ts
server/utils/utils.ts
server/views/pages/assign-a-case.njk

- Pagination Govuk pattern
- Pagination summary MoJ pattern
- Reusable pagination util function
- Unit tests

PSFR-1888: Pagination assign a case

---

server/data/model/resettlementWorker.ts
server/routes/assign-case/__snapshots__/assignCaseController.test.ts.snap
server/routes/index.ts
server/routes/staff-capacity/__snapshots__/staffCapacityController.test.ts.snap
server/routes/staff-capacity/index.ts
server/routes/staff-capacity/staffCapacityController.test.ts
server/routes/staff-capacity/staffCapacityController.ts
server/routes/staff-capacity/staffCapacityView.ts
server/routes/staffDashboard/__snapshots__/staffDashboardController.test.ts.snap
server/services/rpService.ts
server/views/pages/assign-a-case.njk
server/views/pages/staff-capacity.njk
server/views/pages/staff-dashboard.njk

also corrected div on staff dashboard screen when mycases is switched off

PSFR1900 - Staff capacity screen

---

integration_tests/e2e/immediate-needs-report-all-questions.cy.ts
integration_tests/mockApis/rpApi.ts
integration_tests/mockApis/scenarios/john-smith/john-smith-immediate-needs-report-Completed.ts
integration_tests/mockApis/scenarios/john-smith/john-smith-immediate-needs-report.ts
server/data/assessmentStateService.test.ts
server/data/assessmentStateService.ts

** Changed getMergedQuestionsAndAnswers on assessmentStateService
This was looking at answered nested questions which weren't in the cache however it only would ever return at most ONE nested question, have changed to return all answered nested questions.

PSFR-1701 - Cypress test Happy path completed once

---

server/routes/support-need-update/index.ts
server/routes/support-need-update/supportNeedUpdateController.test.ts

Updated the update support need validation following some lessons learned when working on #555

RSP-1858: Added further validation to update support need form

---

server/routes/assign-case/assignCaseController.test.ts
server/routes/assign-case/assignCaseController.ts
server/routes/staffDashboard/__snapshots__/staffDashboardController.test.ts.snap
server/routes/staffDashboard/staffDashboardController.test.ts
server/routes/staffDashboard/staffDashboardController.ts
server/routes/staffDashboard/staffDashboardView.ts
server/services/rpService.test.ts
server/services/rpService.ts
server/views/pages/staff-dashboard.njk

Replaced the immediate needs report filter with a "last report completed" filter
Options are:
* View all (default)
* Immediate needs report
* Pre-release report
* No reports completed

RSP-1977: Amend immediate needs report filter

---

server/routes/staffDashboard/__snapshots__/staffDashboardController.test.ts.snap
server/views/pages/staff-dashboard.njk

The sort and page links needed to include the lastReportCompleted filter

RSP-1977: Fixed losing lastReportCompleted filter on sorting/paging

---

server/routes/accommodation/__snapshots__/accommodationController.test.ts.snap
server/routes/attitudes-thinking-behaviour/__snapshots__/attitudesThinkingBehaviourController.test.ts.snap
server/routes/case-note/__snapshots__/caseNoteController.test.ts.snap
server/routes/children-families-and-communities/__snapshots__/childrenFamiliesCommunitiesController.test.ts.snap
server/routes/drugs-alcohol/__snapshots__/drugsAlcoholController.test.ts.snap
server/routes/education-skills-work/__snapshots__/educationSkillsWorkController.test.ts.snap
server/routes/finance-id-add-id/__snapshots__/financeIdAddIdController.test.ts.snap
server/routes/finance-id-bank-account/__snapshots__/financeIdBankAccountController.test.ts.snap
server/routes/finance-id/__snapshots__/financeIdController.test.ts.snap
server/routes/health-status/__snapshots__/healthStatusController.test.ts.snap
server/routes/licence-image/__snapshots__/licenceImageController.test.ts.snap
server/routes/status-update/__snapshots__/statusUpdateController.test.ts.snap
server/views/partials/profileHeader.njk

RSP-1884: Set 'release date' to 'Unavailable' when null value returned

---

package-lock.json
package.json

Bump govuk-frontend to version 5.10.2

Security update: Bump govuk-frontend to version 5.10.2

---

server/routes/assign-case/index.ts

If read only mode is active, assign a case is disabled

RSP-2046: Added read only mode to assign a case

---

server/routes/finance-id-bank-account/index.ts
server/routes/finance-id/__snapshots__/financeIdController.test.ts.snap
server/routes/finance-id/financeIdController.test.ts
server/routes/finance-id/index.ts
server/routes/testutils/testUtils.ts
server/views/pages/finance-id.njk

In read-only-mode:
- Removes add/update/resubmit/delete bank account buttons
- Displays 'status may be out of date' message against pending bank account applications. 
- Sends all bank account application routes to 404 read-only page.
Note: the 'status may be out of date' message in the content design was red text on a red background.  Agreed with Kate to keep this consistent with other similar text in the UI, and display it as black text on a red background instead.

RSP 2054 - Read Only: Bank Account Application
